### ISSUE TITLE
points accumulated at borders when using adaptive sampling 

### ISSUE THREAD

**Issue by xarthurx** [cemyuksel/cyCodeBase#12]
Similar to issue https://github.com/cemyuksel/cyCodeBase/issues/10
I'm trying to explore the adaptive sampling method using an image-based density function.

When using a smoothly changing density, the results looks cool.
![image](https://user-images.githubusercontent.com/1921878/122015588-84c74980-cdc0-11eb-80b5-c6229e87c8c7.png)
![image](https://user-images.githubusercontent.com/1921878/122015602-885ad080-cdc0-11eb-9b7b-226ea6c8808d.png)

However, when using an image with a sudden change of the density value, the points seems to accumulated at the edges:
![image](https://user-images.githubusercontent.com/1921878/122015787-b6401500-cdc0-11eb-9a09-8baa0ed4438d.png)
![image](https://user-images.githubusercontent.com/1921878/122015828-bf30e680-cdc0-11eb-9c45-8aaa39315552.png)
![image](https://user-images.githubusercontent.com/1921878/122017113-f784f480-cdc1-11eb-96e9-7f09edf30711.png)

The current weight function is like this:
```
    auto wtfunc = [&](const cy::Point3f& p0, const cy::Point3f& p1, float dist2, float d_max) {
      auto d_init = cy::Sqrt(dist2);    // Euclid dist
      auto d = d_init *1 / (1 + den(p0));  // with weight
      return std::pow(1.0 - d / d_max, 8);
    };
```
where the `den(p0)` will get the grayscale value `(0,1)` of the image.

I've tested several different forms of weight function, but this issue seems to persist.

**Comment by cemyuksel** [comment]
Thanks for the comments. These are nice experiments, clearly showing the issue.

There are two problems here:
1. Samples are too densely packed together near one side of the discontinuity.
2. There is a region with no samples on the other side of the discontinuity.

The reason is that the concept of sample density is somewhat ill-defined near discontinuities. Density is defined as the number of samples per area. If you have no samples on one side of the discontinuity, you will have more samples to compensate for it on the other side. Similarly, if you have too many samples on one side, you won't have any on the other side.

That said, in my tests (years ago) I could avoid these problems using a different density function. Using your notation, it would look like something like this:
`auto d = d_init * ( 3 - 2*den(p0) );`
I don't remember much about how I came up with this. See [my Sample Elimination paper (Sec. 5.2)](http://www.cemyuksel.com/research/sampleelimination/sampleelimination.pdf) for more details.
